version: '3.5'

services:
  dogstatsd:
    image: datadog/dogstatsd:7.25.0
    ports:
      - "8125:8125/udp"
    environment:
      - "DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true"
    env_file:
      - .env
